language: minimal

matrix:
  include:
    - name: "7.1"
      env: PHP_VERSION=7.1
    - name: "7.2"
      env: PHP_VERSION=7.2
    - name: "7.3"
      env: PHP_VERSION=7.3

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache

install:
  - docker version
  - sudo pip install docker-compose
  - docker-compose version
  - docker-compose build --build-arg PHP_VERSION=${PHP_VERSION}
  - docker-compose run --rm tests composer install --no-interaction

script:
  - docker-compose run --rm tests ./vendor/bin/phpunit --coverage-clover ./clover.xml
