language: php

branches:
  only:
    - master
    - develop
    - 4.0

php:
  - 5.3
  - 5.4
  - 5.5

services: mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mysql -e 'create database unittest;'
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master
  - composer require mockery/mockery:dev-master
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
