version: '3.5'

services:
    app:
        tty: true
        build: .
        working_dir: /var/www/laravel-mongodb
        environment:
            MONGODB_URI: 'mongodb://mongodb/'
        volumes:
            - .:/var/www/laravel-mongodb
        depends_on:
            mongodb:
                condition: service_healthy

    mongodb:
        container_name: mongodb
        image: mongo:latest
        ports:
            - "27017:27017"
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017 --quiet
            interval: 10s
            timeout: 10s
            retries: 5
